module.exports={
    //这里的配置会和总的配置合并
    configurewebpack:{
        resolve:{
            alias:{
                "assets":"@/assets",
                "common":"@/common",
                "components":"@/components",
                "network":"@/network",
                "network":"@/network",
                "views":"@/views"
            }
        }
    }
}